T1taniumF0rge-Industries-Inc/Software

Security Policy.md
yes my 4th pull request; sorry GamerSoft24
=> Update Security Policy.md

PySoft/Utilities/time clock.py
Why do you have to print every second repetitively to the terminal?
=> Make it cleaner

PySoft/Games/error generator.py
removed the extra tk window, thank me later
=> fixed ya stuff

BatchSoft/software360 aio.bat
using the previous thing it froze my 360AFChrome cuz the lines made it glitch out
=> fix 360afchrome freeze bug

Programs.md
welp time to finally update it to the main branch
=> Programs.md do not close just merge and leave it there for installersoft programs.md

Errors chart.md, PySoft/Calculators/advanced calculator.py, PySoft/Calculators/basic calculator.py, PySoft/Editors/gui-text editor.py, PySoft/Games/code rain.py, PySoft/Games/error generator.py, PySoft/Games/guess a number (top 100).py, PySoft/Games/hangman.py, PySoft/Games/happy new year 2024!!.py, PySoft/Games/login simulator.py, PySoft/Games/rainbow void.py, PySoft/Games/tic-tac-toe.py, PySoft/Utilities/iPCMD.py, PySoft/Utilities/security management system.py
Added error handling to SMS and iPCMD in PySoft. Further error handling on other PySoft programs are currently being worked on.
=> Error handling in PySoft? Issue #34

BatchSoft/Windows/system infos.bat
at least now it's consistent yay!1
=> Make the same changes from Windows360AIO.BAT to SYSTEMINFO.BAT

PySoft/Editors/gui-text editor.py
this program is broken lemme fix it later
=> BROKEN DO NOT COMMIT

Programs.md
=> InstallerSoft: Update Programs.MD

README.md
some NSIS installers are made by me and most of them complain about some virus being on the computer.
just clarification for the others people
=> Make AV detection for some NSIS installers

README.md
planning to add some Moussorgski Tableaux d'une Exposition
=> Update README.md - remove inactive commits because it's a lie

.gitattributes
Please include a summary of the changes and the related issue here. Please also include relevant motivation and context here. List any dependencies that are required for this change. Replace this paragraph with your description.
Please select relevant option by placing an "x" between the square brackets (e.g.: "[x]")
Please tick the checkboxes by placing an "x" between the square brackets (e.g.: "[x]")
All of our programs are carefully made and have been revised and scanned for **any types** of *sneaky viruses or script problems.* They are **100% trustable** and they are **completely safe.** As the programs are very *hardware intensive*, they may take some …
=> Update .gitattributes *.jar TEST

README.md
I have updated the README to mention that we have now reached 1000 commits, and the next milestone (celebration) should happen at 1500 Commits.
- [ √ ] New feature (non-breaking change which adds functionality)
Please tick the checkboxes that you followed
- [ √ ] I have made corresponding changes to the documentation
All of our programs are carefully made and have been revised and scanned for **any types** of *sneaky viruses or script problems.* They are **100% trustable** and they are **completely safe.** As the programs are very *hardware intensive*, they may take some time to load. Please be patient!
| Version | Supported …
=> The Next Milestone - README Update

README.md
test for [!WARNING] markdown tag.
Please tick the checkboxes that you followed
All of our programs are carefully made and have been revised and scanned for **any types** of *sneaky viruses or script problems.* They are **100% trustable** and they are **completely safe.** As the programs are very *hardware intensive*, they may take some time to load. Please be patient!
| Version | Supported          |
| ------- | ------------------ |
| 5.2.x   | :white_check_mark: |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :warning:          |
| 4.1.x   | :x:                |
| < 4.1   | :x:                |
To consider *changing programs …
=> is this how formatting works?

MovieSoft/Sviatoslav Richter/notes_music29032025.md
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN
PULL REQUESTS CAN NOW BE COMMITED TO MAIN …
=> PULL REQUESTS CAN NOW BE COMMITED TO MAIN

.github/workflows/c-cpp.yml, markdown_testing.md
This feature change will I think make the workflows a success, because I keep getting anywhere from 283 to 305 emails a day about workflow failures
Please tick the checkboxes that you followed
All of our programs are carefully made and have been revised and scanned for **any types** of *sneaky viruses or script problems.* They are **100% trustable** and they are **completely safe.** As the programs are very *hardware intensive*, they may take some time to load. Please be patient!
| Version | Supported          |
| ------- | ------------------ |
| 5.2.x   | :white_check_mark: |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | …
=> Update c-cpp.yml - Hopeful workflow fix

PySoft/README.md
Updating stuff with new markdown stuff
Please tick the checkboxes that you followed
All of our programs are carefully made and have been revised and scanned for **any types** of *sneaky viruses or script problems.* They are **100% trustable** and they are **completely safe.** As the programs are very *hardware intensive*, they may take some time to load. Please be patient!
| Version | Supported          |
| ------- | ------------------ |
| 5.2.x   | :white_check_mark: |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :warning:          |
| 4.1.x   | :x:                |
| < 4.1   | :x:                |
To consider *changing …
=> Pysoft note tag update - don't commit now until further notice

LICENSE
June 2023 - September 2025 Licensing agreement
Please include a summary of the changes and the related issue here. Please also include relevant motivation and context here. List any dependencies that are required for this change. Replace this paragraph with your description. 
You can tick any checkboxes by placing an "x" between the square brackets (e.g.: "[x]") or by ticking it/them after you created the pull request.
Please tick the checkboxes that you followed. These are not requirements, those can be seen in the [Contributing Guidelines.](/CONTRIBUTING.md)
This repository and all of its projects are licensed under the terms of the [BSD 3-Clause License](https://github.com/T1taniumF0rge/Software/blob/Main/LICENSE).
=> Update LICENSE Jun23 Sept25

PySoft/Errors chart.md
we should use local links because while they take longer to type when we change repo names or whatever it's much much easier to transport since the links refer to the local repository
Please include a summary of the changes and the related issue here. Please also include relevant motivation and context here. List any dependencies that are required for this change. Replace this paragraph with your description. 
You can tick any checkboxes by placing an "x" between the square brackets (e.g.: "[x]") or by ticking it/them after you created the pull request.
Please tick the checkboxes that you followed. These are not requirements, those can be seen in the [Contributing Guidelines.](/CONTRIBUTING.md)
This repository and all of its projects are licensed under the …
=> Update Errors chart.md for Link Update maybe aww f

CONTRIBUTING.md
more seriously though this is for consistency
Please include a summary of the changes and the related issue here. Please also include relevant motivation and context here. List any dependencies that are required for this change. Replace this paragraph with your description. 
You can tick any checkboxes by placing an "x" between the square brackets (e.g.: "[x]") or by ticking it/them after you created the pull request.
Please tick the checkboxes that you followed. These are not requirements, those can be seen in the [Contributing Guidelines.](/CONTRIBUTING.md)
This repository and all of its projects are licensed under the terms of the [BSD 3-Clause License](https://github.com/T1taniumF0rge/Software/blob/Main/LICENSE).
=> Tu as raison! (bruh I made a PR again???)
